[features]
seeds = true

[programs.localnet]
drill_program_poc = "7CUSJe6g6pbCjyyM5rQEBNPexqp8QTN1wQEdMLSkUFjx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/danmt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
